### ISSUE TITLE
Let's talk

### ISSUE THREAD

**Issue by josch1710** [RespeQt/RespeQt#1]
Hi.

We should coordinate and discuss how we go on with this project.
Where should we meet? IRC?

**Comment by kaelef** [comment]
IRC works - although you'll have to give me details on what server/network and channel to use.  I'm also on Discord - here's a link to my channel/server: 
https://discord.gg/VVh63YB

**Comment by kaelef** [comment]
Here's a Discord group we could use if you'd like to chat:
https://discord.gg/kJ5VgA8

**Comment by josch1710** [comment]
Hi.

Yes, that three names are all me.
I'm Jochen. Computer scientist by trade.
I live in south west Germany (Rheinland-Pfalz, i.e. Rhineland-Palatia).
My email is jochen@joschs-robotics.de.
Discord works as well for me. How about you, Eric?

At the moment, my prime project is RespeQt. There is so much to do.
All the different name convention, code formattings, programming styles.
The code base is mostly C++98, but we can at least do C++11 with the compilers, bundled with Qt 5.6.3. Also, I'm in no way satisfied with the printer emulation.
Also, we urgently need tests. I inserted the capture and replay facility, so that I can debug the printer communication, but it seems broken at the moment and by no means sufficient for testing.

As for collaboration: We should use the issues facilities in Github. Tracking things in AtariAge is really subpar.
