### ISSUE TITLE
Error while building (atascii.cpp)

### ISSUE THREAD

**Issue by ojaksch** [RespeQt/RespeQt#5]
Can't compile anymore, maybe a gcc10 thing (using ArchLinux)?

`g++ -c -pipe -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT -Wall -Wextra -fPIC -DVERSION=\"r5.3\" -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CORE_LIB -I../../RespeQt -I. -isystem /usr/include/qt/QtZlib -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtSerialPort -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o atascii.o ../atascii.cpp

../atascii.cpp: In member function ‘unsigned char Atascii::operator()(const QChar&) const’:

../atascii.cpp:161:15: error: expected type-specifier
  161 |     throw new std::invalid_argument("Unknown unicode mapping");
      |               ^~~

../atascii.cpp:162:1: warning: control reaches end of non-void function [-Wreturn-type]
  162 | }
      | ^
make: *** [Makefile:2522: atascii.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
`

**Comment by jeffgolden** [comment]
I got the same error in Manjaro. I was able to fix it by adding a reference to stdexcept to the atascii.cpp file:
<pre>
#include < stdexcept >
</pre>

**Comment by RespeQt** [comment]
OK, I will add it in the next version so it compiles out of the box.
Thanks to both of you.

**Comment by ojaksch** [comment]
Closing this issue as it's solved. Thanks for fixing.
